export type Modulo = {
  nombre: string
  icon: string
  descripcion: string
  features: string[]
}

export type Sistema = {
  id: string
  nombre: string
  subtitulo: string
  icon: string
  color: string
  gradient: string
  descripcion: string
  highlights: string[]
  modulos: Modulo[]
}

export const SISTEMAS: Sistema[] = [
  {
    id: 'crm-comercial',
    nombre: 'CRM Comercial',
    subtitulo: 'Gestión Comercial & Ventas',
    icon: '💼',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #1e3a8a, #3b82f6)',
    descripcion: 'CRM completo para gestionar todo el ciclo comercial: desde la captación de prospectos hasta el cierre de ventas, con pipeline visual, cotizaciones, email marketing y automatizaciones.',
    highlights: ['Pipeline de Ventas', 'Email Marketing', 'Automatizaciones', 'PQRS Público'],
    modulos: [
      { nombre: 'Dashboard', icon: '📊', descripcion: 'Panel ejecutivo con métricas clave del negocio.', features: ['KPIs: Empresas, Contactos, Oportunidades, Cotizaciones, PQRS', 'Pipeline de oportunidades por etapa con montos', 'Resumen de PQRS por tipo', 'Navegación rápida a cualquier módulo'] },
      { nombre: 'Clientes (Empresas)', icon: '🏢', descripcion: 'Directorio completo de empresas cliente con seguimiento y documentos.', features: ['Ficha completa: NIT, razón social, actividad, ubicación', 'Código de acceso público para PQRS', 'Panel de seguimiento con historial', 'Gestión de documentos adjuntos', 'Reportes con filtros por situación y ciudad'] },
      { nombre: 'Contactos', icon: '👤', descripcion: 'Personas de contacto vinculadas a empresas con nivel de influencia.', features: ['Datos: cargo, departamento, teléfono, email, cumpleaños', 'Nivel de influencia para priorización', 'Contacto principal por empresa', 'Panel de seguimiento y documentos'] },
      { nombre: 'Productos / Servicios', icon: '📦', descripcion: 'Catálogo de productos y servicios con precios para cotizaciones.', features: ['Unidad de medida configurable', 'Precios por producto', 'Estado Activo/Inactivo'] },
      { nombre: 'Oportunidades', icon: '🎯', descripcion: 'Pipeline de ventas con etapas, probabilidad y valor estimado.', features: ['5 etapas: Prospección → Calificación → Propuesta → Negociación → Cierre', 'Monto estimado y probabilidad (25%, 50%, 75%+)', 'Responsable y cliente vinculados', 'Estados: Abierta, En Negociación, Ganada, Perdida', 'Seguimiento con historial completo'] },
      { nombre: 'Cotizaciones', icon: '📝', descripcion: 'Generación de cotizaciones profesionales con líneas de detalle.', features: ['Multi-línea con productos, cantidades y precios', 'Cálculo automático de descuentos e IVA', 'Condiciones de pago y moneda', 'Envío por email al cliente', 'Estados: Borrador, Enviada, Aprobada', 'PDF profesional con logo'] },
      { nombre: 'Prospectos', icon: '🧲', descripcion: 'Captación de leads desde formularios web públicos.', features: ['Formulario público para captación web', 'Origen: Web, Teléfono, Referido', 'Importación de prospectos externos', 'Estados: Nuevo, Contactado, Calificado'] },
      { nombre: 'PQRS', icon: '📩', descripcion: 'Peticiones, Quejas, Reclamos y Sugerencias con formulario público.', features: ['Formulario público con código de acceso del cliente', 'Tipos: Petición, Queja, Reclamo, Sugerencia', 'Prioridad: Baja, Media, Alta', 'Asignación de responsable y seguimiento'] },
      { nombre: 'Tareas', icon: '📝', descripcion: 'Asignación y seguimiento de tareas con vista Kanban.', features: ['Vista Kanban con drag & drop', 'Asignador vs. Ejecutor con fechas límite', 'Notificación por email al ejecutor', 'Estados: Pendiente, En Proceso, Completada, Vencida'] },
      { nombre: 'Email Marketing', icon: '📧', descripcion: 'Campañas de email masivo con diseñador de plantillas.', features: ['Múltiples destinatarios: Clientes, Contactos, Prospectos', 'Editor HTML con imágenes', 'Biblioteca de plantillas reutilizables', 'Estados: Borrador, Enviando, Enviada'] },
      { nombre: 'Diseñador de Correos', icon: '🎨', descripcion: 'Constructor visual de plantillas de email profesionales.', features: ['Diseño visual tipo WYSIWYG', 'Biblioteca de imágenes', 'Plantillas guardadas y reutilizables'] },
      { nombre: 'Automatizaciones', icon: '⚡', descripcion: 'Flujos de trabajo automatizados basados en reglas y triggers.', features: ['Triggers: Registro creado, estado cambiado, programado', 'Condiciones con AND/OR múltiples', 'Acciones: Enviar email, actualizar campo, crear registro', 'Historial de ejecución'] },
      { nombre: 'Correos Enviados', icon: '📬', descripcion: 'Log completo de todas las comunicaciones enviadas.', features: ['Historial con rastreo de apertura', 'Vinculación con orden o cotización'] },
      { nombre: 'Configuración', icon: '⚙️', descripcion: 'Datos empresa, usuarios, permisos, módulos y referencias.', features: ['Usuarios con roles y permisos', 'Tablas de referencia', 'Módulos activables'] },
    ],
  },
  {
    id: 'crm-gtm',
    nombre: 'CRM Grupo GTM',
    subtitulo: 'CRM Empresarial con Base de Datos en la Nube',
    icon: '🎯',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #5b21b6, #8b5cf6)',
    descripcion: 'CRM empresarial con datos persistentes en Supabase PostgreSQL. Gestión completa del ciclo de vida del cliente con tickets de soporte, proyectos, importación masiva desde Excel y agente IA conversacional.',
    highlights: ['Supabase PostgreSQL', 'Tickets Soporte', 'Importar Excel', 'Agente IA'],
    modulos: [
      { nombre: 'Dashboard', icon: '📊', descripcion: 'Panel con KPIs y 4 gráficos analíticos en tiempo real.', features: ['5 KPIs: Clientes, Contactos, Oportunidades, Tareas, Tickets', 'Oportunidades por situación con montos', 'Tareas por estado', 'Tickets por prioridad (donut)', 'Clientes por ciudad (barras)'] },
      { nombre: 'Empresa', icon: '🏛️', descripcion: 'Gestión de entidades corporativas con logo.', features: ['NIT, correo, representante legal', 'Logo con preview', 'Múltiples empresas'] },
      { nombre: 'Clientes', icon: '🏢', descripcion: 'Base de datos con integridad referencial en PostgreSQL.', features: ['Ficha con tipo de cliente y situación', 'Datos en Supabase PostgreSQL', 'Formulario multi-sección', 'Exportación PDF/Excel/CSV'] },
      { nombre: 'Contactos', icon: '👤', descripcion: 'Personas vinculadas a clientes con nivel de influencia.', features: ['Departamento, cargo, nivel de influencia', 'Vinculación directa con empresa', 'Server Actions seguros'] },
      { nombre: 'Oportunidades', icon: '💰', descripcion: 'Pipeline persistente con montos por moneda.', features: ['Adjudicada, En Proceso, Ganada, Perdida, Cerrada', 'Montos con colores por estado', 'Datos persistentes en la nube'] },
      { nombre: 'Tareas', icon: '📝', descripcion: 'Doble vista: tabla y Kanban.', features: ['Vista tabla y Kanban alternables', 'Estados con colores', 'Asignación con paginación'] },
      { nombre: 'Tickets de Soporte', icon: '🎫', descripcion: 'Sistema de tickets con priorización.', features: ['Prioridades: Baja, Media, Alta, Crítica', 'Categorización por tipo de incidencia', 'Estadísticas en dashboard'] },
      { nombre: 'Proyectos', icon: '📂', descripcion: 'Gestión de proyectos con estado y seguimiento.', features: ['Creación y seguimiento', 'Estado vinculado a referencia', 'Detalle con fechas'] },
      { nombre: 'Agente IA', icon: '🤖', descripcion: 'Asistente conversacional con voz.', features: ['Chat por texto y voz en español', 'Consultas sobre datos del CRM', 'Respuestas en tiempo real'] },
      { nombre: 'Importar Excel', icon: '📥', descripcion: 'Importación masiva desde archivos Excel.', features: ['Múltiples módulos soportados', 'Validación durante importación', 'Procesamiento por lotes'] },
      { nombre: 'Email Marketing', icon: '📧', descripcion: 'Campañas con diseñador y plantillas.', features: ['Destinatarios múltiples', 'Diseñador visual', 'Seguimiento de estado'] },
      { nombre: 'Automatizaciones', icon: '⚡', descripcion: 'Reglas de automatización para procesos.', features: ['Triggers y condiciones personalizables', 'Acciones automáticas', 'Activación/desactivación'] },
      { nombre: 'Configuración', icon: '⚙️', descripcion: '16 tablas de referencia + usuarios + permisos.', features: ['16 tablas referenciales', 'Usuarios con permisos', 'Módulos activables', 'Personal comercial'] },
    ],
  },
  {
    id: 'gestion-inventario',
    nombre: 'Gestión de Inventario',
    subtitulo: 'Control de Inventario, Compras & Producción',
    icon: '📦',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #065f46, #10b981)',
    descripcion: 'Sistema integral para controlar inventario, compras, producción y operaciones. Productos con serialización, múltiples bodegas, transferencias, fórmulas de producción, centros de costo y asistente IA con voz.',
    highlights: ['25 Módulos', 'Producción', 'Multi-Bodega', 'Asistente IA'],
    modulos: [
      { nombre: 'Dashboard', icon: '📊', descripcion: 'Indicadores clave de inventario en tiempo real.', features: ['KPIs: Productos, Proveedores, Órdenes, Recepciones, Bodegas', 'Unidades en stock, valor total, bajo mínimo', 'Órdenes por estado con montos', 'Asistente de voz integrado'] },
      { nombre: 'Productos', icon: '📦', descripcion: 'Catálogo con código automático y reportes avanzados.', features: ['Código PROD-00001 con validación de duplicados', 'Tipo Inventario, Categoría, Grupo, Sub-Grupo', 'Existencias con mín/máx y último costo', 'Códigos de barras y serialización', 'Reportes PDF/Excel', 'Búsqueda por voz'] },
      { nombre: 'Proveedores', icon: '🏢', descripcion: 'Directorio con contacto y clasificación.', features: ['Identificación, actividad, contacto, ciudad, país', 'Estados: Activo, Bloqueado, Inactivo', 'Referencias con notas', 'Reportes y búsqueda por voz'] },
      { nombre: 'Órdenes de Compra', icon: '🛒', descripcion: 'Creación y envío con cálculo de impuestos.', features: ['Numeración ORD-00001', 'Multi-línea con subtotales e IVA', 'Envío por email al proveedor', 'Pendiente → Aprobada → Recibida → Rechazada', 'PDF con logo', 'Rastreo de correos'] },
      { nombre: 'Recepción de Facturas', icon: '📋', descripcion: 'Recepción parcial o total contra órdenes.', features: ['Recepción línea por línea', 'Monitoreo recibido vs. pendiente', 'Actualización automática de costos'] },
      { nombre: 'Bodegas', icon: '🏭', descripcion: 'Almacenes con movimientos y saldos.', features: ['Registro con ubicación y contacto', 'Historial: Entrada/Salida/Ajuste', 'Saldos por bodega y producto', 'Activa, Mantenimiento, Cerrada'] },
      { nombre: 'Transferencias', icon: '🔄', descripcion: 'Traslados entre bodegas con aprobación.', features: ['TRF-00001 multi-línea', 'Bodega origen y destino', 'Borrador → Aprobada → Completada', 'PDF con firmas'] },
      { nombre: 'Salidas de Almacén', icon: '📤', descripcion: 'Salidas con centro de costo y autorizador.', features: ['Deducción automática de inventario', 'Centro de costo', 'Flujo de aprobación', 'PDF estandarizado'] },
      { nombre: 'Ajustes de Inventario', icon: '⚖️', descripcion: 'Correcciones con clasificación y motivo.', features: ['Adición o sustracción', 'Bodega y producto', 'Aprobación con autorizador', 'PDF/Excel'] },
      { nombre: 'Carga Inicial', icon: '📥', descripcion: 'Carga masiva al arrancar una bodega.', features: ['Multi-línea con cantidades y costos', 'CII-00001', 'Bodega destino', 'PDF con firma'] },
      { nombre: 'Fórmulas de Producción', icon: '🧪', descripcion: 'Recetas de materias primas por producto terminado.', features: ['FORM-00001', 'Multi-ingrediente', 'Solo productos tipo Producto Terminado', 'Activa/Inactiva'] },
      { nombre: 'Órdenes de Producción', icon: '📋', descripcion: 'Órdenes desde fórmulas con requerimientos.', features: ['Generación desde fórmula', 'Multiplicador de ingredientes', 'Verificación de stock', 'Pendiente → En Proceso → Completada'] },
      { nombre: 'Ejecución de Producción', icon: '▶️', descripcion: 'Consumo real y confirmación de fabricación.', features: ['Consumo con ajuste', 'Deducción de materias primas', 'Incremento de producto terminado', 'Verificación de stock'] },
      { nombre: 'Ajustes Materia Prima', icon: '⚖️', descripcion: 'Entrada/salida por daño, pérdida o pruebas.', features: ['AMP-00001', 'Motivo documentado', 'Inventario en tiempo real', 'Responsable'] },
      { nombre: 'Centros de Costo', icon: '💰', descripcion: 'Estructura para asignar gastos de material.', features: ['Código y descripción', 'Activo/Inactivo', 'PDF/Excel', 'Usado en Salidas'] },
      { nombre: 'Tareas', icon: '📝', descripcion: 'Asignación con vista Kanban.', features: ['Kanban drag & drop', 'Asignador vs. Ejecutor', 'Email al ejecutor', 'Pendiente, En Proceso, Completada, Vencida'] },
      { nombre: 'Personal Empresa', icon: '👥', descripcion: 'Directorio de empleados.', features: ['Nombre, email, teléfono', 'Prevención de duplicados', 'Integración con Tareas'] },
      { nombre: 'Órdenes de Pedido', icon: '📄', descripcion: 'Solicitudes con envío por correo.', features: ['Multi-línea', 'Proveedor y bodega', 'Envío por email', 'Correos integrados'] },
      { nombre: 'Correos Enviados', icon: '📧', descripcion: 'Log de comunicaciones del sistema.', features: ['Rastreo: Enviado / Abierto', 'Vinculación con orden', 'Búsqueda avanzada'] },
      { nombre: 'Agente IA', icon: '🤖', descripcion: 'Asistente con reconocimiento de voz.', features: ['Voz en español', 'Síntesis de texto', 'Inventario, órdenes, tareas', 'Historial de conversación'] },
      { nombre: 'Configuración', icon: '⚙️', descripcion: 'Empresa, usuarios, permisos, módulos, referencias.', features: ['Logo para PDFs y correos', 'Servidor de correo', 'Roles y permisos por módulo', 'Módulos activables', 'Tablas de referencias'] },
    ],
  },
  {
    id: 'calzado-ropa',
    nombre: 'Calzado & Ropa',
    subtitulo: 'Inventario Retail con Variantes y Punto de Venta',
    icon: '👟',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #92400e, #f59e0b)',
    descripcion: 'Sistema retail especializado en calzado y ropa. Variantes de talla y color, SKU único, código de barras, punto de venta con múltiples métodos de pago y gestión multi-bodega.',
    highlights: ['Variantes Talla/Color', 'Punto de Venta', 'Códigos de Barras', 'Multi-Bodega'],
    modulos: [
      { nombre: 'Dashboard', icon: '📊', descripcion: 'Métricas de stock, valor y alertas.', features: ['Unidades en stock y valor total', 'Variantes bajo mínimo', 'Órdenes pendientes', 'Bodegas activas'] },
      { nombre: 'Productos con Variantes', icon: '📦', descripcion: 'Catálogo con talla/color y SKU automático.', features: ['Código PRD-00001', 'Variantes por color + talla', 'SKU: PRD-00001-BLA-38', 'Código de barras por variante', 'Stock, costo y precio por variante', 'Mín/máx por variante', 'Tipo: Niño, Niña, Hombre, Mujer, Unisex', 'Categoría: Calzado, Ropa, Accesorios'] },
      { nombre: 'Punto de Venta (POS)', icon: '💳', descripcion: 'Interfaz de venta rápida con impuestos.', features: ['Selección por variante', 'Múltiples métodos de pago', 'Cálculo de impuestos', 'Impresión de recibo', 'Cierre de caja diario'] },
      { nombre: 'Clientes', icon: '🧑‍💼', descripcion: 'Base de datos para ventas y pedidos.', features: ['Contacto completo', 'Tipo: minorista, mayorista', 'Activo/Inactivo'] },
      { nombre: 'Pedidos de Cliente', icon: '📄', descripcion: 'Órdenes de cliente con seguimiento.', features: ['Estado del pedido', 'Información de entrega', 'Cumplimiento'] },
      { nombre: 'PQRS', icon: '📩', descripcion: 'Peticiones, Quejas, Reclamos y Sugerencias.', features: ['Abierto, En Proceso, Cerrado', 'Seguimiento y respuesta', 'Historial por cliente'] },
      { nombre: 'Proveedores', icon: '🏢', descripcion: 'Directorio de proveedores.', features: ['Contacto y referencias', 'Actividad y ubicación', 'Estados y reportes'] },
      { nombre: 'Órdenes de Compra', icon: '🛒', descripcion: 'Compras con detalle por variante.', features: ['Desglose color/talla/cantidad', 'Flujo de aprobación', 'Recepción parcial/total', 'Unidad: Par o Unidad'] },
      { nombre: 'Recepción de Facturas', icon: '📋', descripcion: 'Ingreso a bodega contra órdenes.', features: ['Parcial o completa', 'Control de calidad', 'Stock automático'] },
      { nombre: 'Bodegas', icon: '🏭', descripcion: 'Múltiples almacenes con saldos.', features: ['Saldos por bodega y variante', 'Activa, Mantenimiento, Cerrada'] },
      { nombre: 'Transferencias', icon: '🔄', descripcion: 'Traslados con detalle de variantes.', features: ['Origen y destino', 'Aprobación', 'Trazabilidad completa'] },
      { nombre: 'Salidas de Almacén', icon: '📤', descripcion: 'Salidas controladas.', features: ['Deducción de inventario', 'Centro de costo', 'Autorizador'] },
      { nombre: 'Ajustes de Inventario', icon: '⚖️', descripcion: 'Correcciones por conteo, daño o pérdida.', features: ['Adición o sustracción', 'Motivo documentado', 'Autorización requerida'] },
      { nombre: 'Carga Inicial', icon: '📥', descripcion: 'Carga masiva de inventario.', features: ['Importación desde Excel', 'Validación', 'Bodega destino'] },
      { nombre: 'Configuración', icon: '⚙️', descripcion: 'Empresa, usuarios, referencias, módulos.', features: ['20+ tablas incluyendo colores y tallas', 'Etiquetas con código de barras/QR', 'Roles y permisos', 'Módulos activables'] },
    ],
  },
  {
    id: 'portal-inmobiliario',
    nombre: 'Portal Inmobiliario',
    subtitulo: 'Gestión de Propiedades & Catálogo Público',
    icon: '🏢',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #9d174d, #ec4899)',
    descripcion: 'Portal inmobiliario con catálogo público para compradores y panel administrativo. Propiedades con galería, clientes con presupuesto, equipo comercial por zonas, cotizaciones, contratos y búsqueda por voz.',
    highlights: ['Catálogo Público', 'Galería Fotos', 'Contratos', 'Búsqueda por Voz'],
    modulos: [
      { nombre: 'Catálogo Público', icon: '🌐', descripcion: 'Portal web sin login para explorar propiedades.', features: ['Listado sin autenticación', 'Filtros: tipo, ciudad, zona, modalidad', 'Ficha detallada con galería', 'Diseño responsive'] },
      { nombre: 'Dashboard', icon: '📊', descripcion: 'Métricas de propiedades y operaciones.', features: ['Disponibles, en venta, en arriendo', 'Comerciales activos', 'Cotizaciones y contratos', 'Propiedades por estado'] },
      { nombre: 'Propiedades', icon: '🏠', descripcion: 'Inmuebles con galería y ficha PDF.', features: ['Tipos: Apartamento, Casa, Oficina, Local, Lote, Bodega', 'Venta, Alquiler o Ambos', 'Galería hasta 5 imágenes', 'Área, habitaciones, baños, parqueaderos', 'Ficha PDF profesional', 'Disponible, Vendida, Reservada, Alquilada'] },
      { nombre: 'Comerciales', icon: '👔', descripcion: 'Asesores inmobiliarios por zona.', features: ['Nombre, email, cargo, departamento', 'Zonas asignadas', 'Foto con compresión', 'Activo/Inactivo'] },
      { nombre: 'Clientes / Prospectos', icon: '👥', descripcion: 'Compradores con presupuesto y preferencias.', features: ['Cliente o Prospecto', 'Interés: Compra o Alquiler', 'Presupuesto mín/máx con moneda', 'Ciudad, zona y tipo preferido', 'Asesor asignado'] },
      { nombre: 'Cotizaciones', icon: '📝', descripcion: 'Ofertas con envío por email.', features: ['Cliente + propiedad + asesor', 'Precio y condiciones', 'Envío por email', 'Pendiente, Aceptada, Rechazada'] },
      { nombre: 'Contratos', icon: '📑', descripcion: 'Contratos de venta y alquiler con PDF.', features: ['Tipo: Venta o Alquiler', 'Monto, duración, fechas', 'Condiciones y observaciones', 'Múltiples documentos adjuntos', 'PDF generado', 'Borrador, Vigente, Cancelado'] },
      { nombre: 'Solicitudes', icon: '📩', descripcion: 'Consultas de interesados.', features: ['Datos del solicitante y mensaje', 'Propiedad vinculada', 'Asesor con notas', 'Nueva, En Revisión, Respondida, Cerrada'] },
      { nombre: 'Configuración', icon: '⚙️', descripcion: 'Monedas, tipos, ciudades, zonas.', features: ['Monedas con símbolos', 'Tipos de propiedad', 'Ciudades y zonas', 'Datos de empresa'] },
    ],
  },
  {
    id: 'homeux',
    nombre: 'HomeUX',
    subtitulo: 'Gestión de Servicios del Hogar',
    icon: '🏠',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #9a3412, #f97316)',
    descripcion: 'Sistema para empresas de servicios del hogar. Ciclo completo desde solicitud hasta cotización, con catálogo de productos, personal técnico con habilidades y certificaciones.',
    highlights: ['Solicitudes', 'Cotizaciones', 'Personal Técnico', 'Habilidades'],
    modulos: [
      { nombre: 'Dashboard', icon: '📊', descripcion: 'Métricas de solicitudes, clientes y personal.', features: ['Solicitudes nuevas y en proceso', 'Clientes activos', 'Cotizaciones aprobadas', 'Personal activo'] },
      { nombre: 'Solicitudes de Servicio', icon: '🔧', descripcion: 'Registro con tipo de trabajo e imágenes.', features: ['Código SOL-00001', 'Tipo de trabajo configurable', 'Datos del cliente y ubicación', 'Imágenes adjuntas', 'Nueva → En Proceso → Completada → Cancelada', 'PDF/Excel/Impresión'] },
      { nombre: 'Clientes / Prospectos', icon: '👥', descripcion: 'Base de datos con datos de vivienda.', features: ['Código CLI-00001', 'Datos personales y contacto', 'Tipo de vivienda, urbanización', 'Estado civil y situación', 'Foto de perfil'] },
      { nombre: 'Productos y Materiales', icon: '📦', descripcion: 'Catálogo con unidades variadas.', features: ['Código PROD-00001', 'Precio unitario', 'Unidades: m2, litro, galón, kg, rollo, caja, servicio', 'Activo/Inactivo'] },
      { nombre: 'Cotizaciones', icon: '📝', descripcion: 'Presupuestos con líneas de detalle.', features: ['Código COT-00001', 'Vinculación con cliente y solicitud', 'Líneas con productos y cantidades', 'Precio auto-poblado', 'Cálculo de totales', 'Pendiente, Aprobada, Rechazada'] },
      { nombre: 'Personal Técnico', icon: '👷', descripcion: 'Trabajadores con habilidades y formación.', features: ['Código PER-00001', 'Tipo: Persona o Empresa', 'Formación y capacitación', 'Selección múltiple de habilidades', 'Experiencia previa', 'Foto y referencias'] },
      { nombre: 'Configuración', icon: '⚙️', descripcion: '11 tablas de referencia.', features: ['Países y ciudades', 'Tipos de trabajo y vivienda', 'Identificaciones y estados civiles', 'Formaciones y habilidades'] },
    ],
  },
  {
    id: 'portales-publicos',
    nombre: 'Portales Públicos',
    subtitulo: 'Formularios y Catálogos sin Login — Conectados al Admin',
    icon: '🌐',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #0e7490, #06b6d4)',
    descripcion: 'Páginas públicas accesibles sin autenticación que alimentan directamente los sistemas administrativos. Captación de prospectos, atención al cliente vía PQRS, y catálogo inmobiliario con solicitudes de contacto.',
    highlights: ['Sin Login', 'Formularios Públicos', 'Catálogo Web', 'Conectados al CRM'],
    modulos: [
      { nombre: 'Formulario de Prospectos', icon: '🧲', descripcion: 'Formulario web público para que cualquier persona envíe sus datos e interés comercial. Los prospectos llegan al CRM Comercial para seguimiento.', features: ['Campos: Nombre, Apellido, Empresa, Correo, Móvil, Requerimiento', 'Validación en tiempo real con feedback visual', 'Pantalla de éxito con confirmación', 'Email automático de confirmación al prospecto vía SMTP', 'Los datos se almacenan como prospectos externos', 'El admin los importa al CRM con código PRS-XXXXX', 'Origen marcado como "Formulario Web"', 'Estado inicial: "Sin Contactar"'] },
      { nombre: 'PQRS Público', icon: '📩', descripcion: 'Sistema de Peticiones, Quejas, Reclamos y Sugerencias para clientes existentes. Requiere código de acceso único por cliente.', features: ['Paso 1: Validación con código de acceso del cliente (6-10 caracteres)', 'Paso 2: Formulario PQRS con datos del cliente auto-poblados', 'Tipos con iconos: Petición, Queja, Reclamo, Sugerencia', 'Prioridad con colores: Baja (verde), Media (amarillo), Alta (naranja), Urgente (rojo)', 'Campos: Fecha aviso, hora, persona que avisa, móvil, detalle', 'Genera número de radicado único: RAD-YYYYMMDD-0001', 'El cliente usa el radicado para dar seguimiento', 'El admin importa los PQRS al CRM para gestión interna', 'Puede enviar múltiples PQRS sin re-validar el código'] },
      { nombre: 'Portal Inmobiliario — Inicio', icon: '🏠', descripcion: 'Landing page pública del portal de propiedades con estadísticas y propiedades destacadas.', features: ['Hero con llamada a la acción "Ver Propiedades"', 'Estadísticas en vivo: propiedades disponibles, ciudades, tipos, zonas', 'Grid de 6 propiedades destacadas con imagen, tipo, precio y specs', 'Cada tarjeta muestra: habitaciones, baños, metros cuadrados', 'Link directo a ficha detallada de cada propiedad', 'Diseño responsive para móviles y tablets'] },
      { nombre: 'Portal Inmobiliario — Catálogo', icon: '🔍', descripcion: 'Catálogo completo y filtrable de todas las propiedades disponibles, sin necesidad de login.', features: ['Búsqueda libre por nombre, dirección, ciudad o código', 'Filtro por tipo de propiedad', 'Filtro por ciudad/municipio', 'Filtro por zona (dinámico según ciudad seleccionada)', 'Filtro por modalidad: Venta, Alquiler, Ambos', 'Botón "Limpiar filtros" para reiniciar', 'Contador de resultados en tiempo real', 'Grid responsive: 1/2/3 columnas según pantalla', 'Tarjetas con imagen, badge de tipo, precio y características'] },
      { nombre: 'Portal Inmobiliario — Ficha de Propiedad', icon: '🏡', descripcion: 'Página detallada de cada propiedad con galería de fotos, especificaciones, asesor asignado y formulario de contacto.', features: ['Galería de imágenes con thumbnails navegables', 'Badges de tipo y modalidad (Venta/Alquiler)', 'Precio de venta y/o alquiler con moneda', 'Características: área m2, habitaciones, baños, parqueaderos, balcones', 'Amenidades y descripción completa', 'Tarjeta del asesor asignado con foto, teléfono y email', 'Formulario "¿Te interesa esta propiedad?"', 'Genera solicitud automática (SOL-00001) vinculada a la propiedad', 'Se asigna al asesor de la propiedad automáticamente', 'Pantalla de éxito con confirmación'] },
    ],
  },
]
